name: Emoji Check

on:
  push:
    branches:
      - main

jobs:
  check-emojis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check emojis in Markdown files
      uses: alaeddineth/check-emojis-action@v1
